steps:
 # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sit737-23t1-dharmaraja-5f2a74e/contactsapp:$COMMIT_SHA'
      - '.'

  # Push container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/sit737-23t1-dharmaraja-5f2a74e/contactsapp:$COMMIT_SHA'
  
  # Deploy container image to GKE and delete existing pods
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=deployment.yaml"
      - "--location=us-central1-a"
      - "--cluster=mongo-cluster"

