apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'contactsapp'
        scrape_interval: 5s
        static_configs:
          - targets: ['contactsapp:80']
